/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElIcon: typeof import('element-plus/es')['ElIcon'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElMenu: typeof import('element-plus/es')['ElMenu'];
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem'];
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar'];
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu'];
    ElText: typeof import('element-plus/es')['ElText'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default'];
    Valicode: typeof import('./src/components/valicode/index.vue')['default'];
  }
}
